---
title: "Lab7"
author: GEO200CN, spring 2017
output: html_document
---

# Lab 7: Distance + Spatial Influence
In this lab you will continue to practice point pattern analysis with R. If the concepts you are working with feel unclear or unfamiliar that’s a good hint that you might want to re-review Chapt 5+6 of OSU and your lecture notes.

Start by reading and following along with the Distance section, and the first three subsections (Adjacency, Two Nearest Neighbors, Weight Matrix) of the Spatial Influence section of Chapt 2. Scale and Distance in the Spatial Data Analysis on RSpatial. Then respond to the questions below. [see the lab handout for greater details]

1. Distance [http://rspatial.org/analysis/rst/2-scale_distance.html#distance]
a) [Question 4 in the text] Show R code to make a cluster dendogram summarizing the distances between these six sites, and plot it. See ?hclust
[Remember dendogram are a tree of branching diagram that illustrates clustering or similarity]
b) [Question 5 in the text] What is the unit of the values in “gdis”? See ?pointDistance

2.Spatial Influence [http://rspatial.org/analysis/rst/2-scale_distance.html#spatial-influence]
a) In preparing the two nearest neighbors matrix, why do you select columns 2 and 3, and not column 1?

3. Distance and Weight Matrix UCD Places
a) Using the same UCD places we used in Lab4 [UCplaces.csv] you will calculate a binary distance matrix that defines neighbors as places closer than 500 meters.
b) Which places are defined as neighbors to Hunt Hall?
Bonus) Calculate a continuous value matrix for the same data, with distances measured in meters, and where rows sum to 1.

Upload to smartsite an Rmarkdown and HTML file. 

Due: Wednesday, May 3, 9a



